#!/usr/bin/env python3
"""
สร้างไฟล์ C header จาก thai_words_filtered.txt สำหรับฝังเข้า flash
ใช้ run ครั้งเดียว (ไม่ใช่ pre-build script) เพราะพจนานุกรมไม่เปลี่ยนบ่อย
เหมือนไฟล์ generated/hyph-*.trie.h อื่นๆ ในโปรเจกต์

รูปแบบข้อมูล (เพื่อลดขนาด flash ~50%): prefix (front) compression
  - คำถูก sort ตาม UTF-8 byte order แล้วเก็บเป็น "record" ต่อเนื่องกัน
  - แต่ละ record = [1 byte: ความยาว prefix ที่ใช้ร่วมกับคำก่อนหน้า][suffix bytes][0x00]
  - ทุกๆ kCheckpointStride คำ จะ "reset" ให้ shared_len = 0 (เก็บคำเต็ม) เป็น checkpoint
    เพื่อให้ทำ binary search ข้าม checkpoint ได้ แล้วค่อยไล่ scan สั้นๆ ภายใน block

วิธีรัน (ที่ root ของ repo):
    python3 gen_thai_words_header.py

สร้างไฟล์: lib/Epub/Epub/hyphenation/generated/thai_words.h
"""

import os

SRC = "lib/Epub/Epub/hyphenation/thai_words_filtered.txt"
DST_DIR = "lib/Epub/Epub/hyphenation/generated"
DST = os.path.join(DST_DIR, "thai_words.h")

CHECKPOINT_STRIDE = 32  # words per checkpoint block; tune for size vs. lookup speed tradeoff


def common_prefix_len(a: bytes, b: bytes) -> int:
    n = min(len(a), len(b))
    i = 0
    while i < n and a[i] == b[i]:
        i += 1
    return i


def byte_to_token(b: int) -> str:
    """Escape a single byte as a self-contained C string-literal token ("\\xNN" or "\\0").

    Every byte in the blob - including the shared-prefix-length byte, which is NOT a
    printable character - is escaped this way uniformly. This is deliberate: each token
    always starts with a backslash, so tokens can be concatenated in any order without
    the compiler's unbounded \\x-hex-digit-consumption ever swallowing part of the next
    token (the exact bug that broke the previous generator version).
    """
    if b == 0:
        return "\\0"
    return f"\\x{b:02x}"


def main():
    with open(SRC, encoding="utf-8") as f:
        words = [line.strip() for line in f if line.strip()]

    words.sort()  # ensure UTF-8 byte order (matches codepoint order) for binary search

    os.makedirs(DST_DIR, exist_ok=True)

    blob_tokens = []
    checkpoint_offsets = []
    current_offset = 0
    prev_encoded = b""

    for idx, w in enumerate(words):
        encoded = w.encode("utf-8")
        is_checkpoint = (idx % CHECKPOINT_STRIDE == 0)
        shared = 0 if is_checkpoint else common_prefix_len(prev_encoded, encoded)
        suffix = encoded[shared:]

        if is_checkpoint:
            checkpoint_offsets.append(current_offset)

        blob_tokens.append(byte_to_token(shared))
        for byte in suffix:
            blob_tokens.append(byte_to_token(byte))
        blob_tokens.append("\\0")

        current_offset += 1 + len(suffix) + 1
        prev_encoded = encoded

    with open(DST, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by gen_thai_words_header.py - do not edit by hand.\n")
        f.write("// Source word list: PyThaiNLP words_th.txt (CC0-1.0 Public Domain)\n")
        f.write("// https://github.com/PyThaiNLP/pythainlp\n")
        f.write("//\n")
        f.write("// Data layout: prefix (front) compressed word list. See lookup code in\n")
        f.write("// Hyphenator.cpp (thaiWordExists) for how to decode/search this structure.\n")
        f.write("#pragma once\n\n")
        f.write("#include <cstdint>\n\n")
        f.write("namespace ThaiWords {\n\n")
        f.write(f"constexpr size_t kThaiWordCount = {len(words)};\n")
        f.write(f"constexpr size_t kThaiCheckpointStride = {CHECKPOINT_STRIDE};\n")
        f.write(f"constexpr size_t kThaiCheckpointCount = {len(checkpoint_offsets)};\n\n")

        f.write("// Prefix-compressed word records, concatenated. Each record is:\n")
        f.write("//   [1 byte: shared-prefix length with previous word (0 at checkpoints)]\n")
        f.write("//   [suffix bytes to append after the shared prefix]\n")
        f.write("//   [0x00 terminator]\n")
        f.write("static const char kThaiWordsBlob[] =\n")
        max_line_chars = 200
        line_tokens = []
        line_len = 0
        for tok in blob_tokens:
            if line_tokens and line_len + len(tok) > max_line_chars:
                f.write(f'    "{"".join(line_tokens)}"\n')
                line_tokens = []
                line_len = 0
            line_tokens.append(tok)
            line_len += len(tok)
        if line_tokens:
            f.write(f'    "{"".join(line_tokens)}"\n')
        f.write(";\n\n")

        f.write("// Byte offset within kThaiWordsBlob of the start of each checkpoint record.\n")
        f.write("// Checkpoint i covers words [i*kThaiCheckpointStride, (i+1)*kThaiCheckpointStride)\n")
        f.write("// (the last checkpoint's block may be shorter). kThaiCheckpointCount entries.\n")
        f.write("static const uint32_t kThaiCheckpointOffsets[] = {\n")
        for i in range(0, len(checkpoint_offsets), 16):
            row = ", ".join(str(o) for o in checkpoint_offsets[i:i + 16])
            f.write(f"    {row},\n")
        f.write("};\n\n")
        f.write("}  // namespace ThaiWords\n")

    actual_blob_bytes = current_offset
    checkpoint_bytes = len(checkpoint_offsets) * 4
    print(f"เขียนไฟล์: {DST}")
    print(f"จำนวนคำ: {len(words)}")
    print(f"checkpoint ทุกๆ {CHECKPOINT_STRIDE} คำ ({len(checkpoint_offsets)} checkpoints)")
    print(f"ขนาด blob: {actual_blob_bytes / 1024:.1f} KB")
    print(f"ขนาด checkpoint table: {checkpoint_bytes / 1024:.1f} KB")
    print(f"ขนาดรวมโดยประมาณ: {(actual_blob_bytes + checkpoint_bytes) / 1024:.1f} KB")


if __name__ == "__main__":
    main()
