import os
import sys

DEFAULT_SRC = os.path.join("src", "images", "Logo-steroids.png")
OUTPUT = os.path.join("src", "network", "html", "LogoPng.generated.h")


def write_if_changed(path, content):
    if os.path.exists(path):
        with open(path, "r", encoding="utf-8") as f:
            if f.read() == content:
                return False
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)
    return True


def render_header(data):
    lines = [
        "// THIS FILE IS AUTOGENERATED, DO NOT EDIT MANUALLY",
        "// Generated by scripts/embed_logo_png.py",
        "",
        "#pragma once",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "static const char LogoPng[] PROGMEM = {",
    ]
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_values = ", ".join(f"0x{b:02x}" for b in chunk)
        lines.append(f"  {hex_values},")
    lines.extend([
        "};",
        "",
        f"constexpr size_t LogoPngSize = {len(data)};",
    ])
    return "\n".join(lines) + "\n"


def main():
    src = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SRC
    if not os.path.isfile(src):
        print(f"error: source PNG not found: {src}", file=sys.stderr)
        sys.exit(1)
    with open(src, "rb") as f:
        data = f.read()
    header = render_header(data)
    if write_if_changed(OUTPUT, header):
        print(f"Generated: {OUTPUT}  ({len(data)} bytes, from {src})")
    else:
        print(f"Up to date: {OUTPUT}")


if __name__ == "__main__":
    main()
